// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../debug/js_dev/example.js', ['com.mycompany.Example'], ['goog.array', 'goog.dom']);
goog.addDependency('../../../../debug/js_dev/main.js', ['com.mycompany.Main'], ['com.mycompany.Example']);
