// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/example.js', ['foo.Example'], ['goog.array', 'goog.dom']);
goog.addDependency('../../../../development/js_dev/main.js', ['foo.Main'], ['foo.Example']);
