/**
 * @fileoverview An entry point of the web app. This script was automatically
 * generated by googkit.
 */


goog.provide('googkit_index'); /*@provide_main@*/

goog.require('foo.Example');


// TODO: Write your code here
var example = new foo.Example();
example.doSomething();
